### ISSUE TITLE
Is it possible to use structs in different module(/repository) for input/output?

### ISSUE THREAD

**Issue by jorygeerts** [mikunalpha/goas#6]
I have a repository (say github.com/foo/bar) that contains types that I want to use as output for my handlers. I've tried the following:

1.  `@Failure 400 object bar.MyError`
2.  `@Failure 400 object github.com/foo/bar/MyError`
3.  `@Failure 400 object github.com/foo/bar/bar.MyError`

The resulting swagger JSON for all of these is this:
```json
"components": {
    "schemas": {
      "": {}
    }
  }
```

So `goas` sees there is something, it just can't do anything useful with it.

The type is imported and used in the file where its referenced by the godoc.

Am I doing something wrong? Or is this not supported?

**Comment by mikunalpha** [comment]
Try to `import "github.com/foo/bar"`  or `import _ "github.com/foo/bar"` ?

**Comment by jorygeerts** [comment]
I have that as an import, but it doesn't work.

I've been debugging this, and one thing I'm noticing is that in some places the package name that comes out of the AST is separated by a \ instead of a /, but in other places it is separated by a /, so that might be why the correct package can't be found.

I'm guessing this is a Windows only issue. Are you using this on a Windows system, @mikunalpha? If you're not, I might be looking in the right direction.

**Comment by jorygeerts** [comment]
After some more digging around, the path issues caused my problems. I've created a PR that solves this issue.

**Comment by mikunalpha** [comment]
I have been developing on Linux.
